### ISSUE TITLE
Colorfy chokes on default option for '-f'

### ISSUE THREAD

**Issue by ChristophWWagner** [EMS-TU-Ilmenau/colorfy#4]
When not specifying any argument for `-f`, colorfy cannot handle it correctly, probably to misinterpreting the default string as list. As the usage syntax suggests, it should be able to deal with this kind of invocation without problems.

```
user:~/Git/github/colorfy/demo$ colorfy -p colors -o bla
Traceback (most recent call last):
File "/home/user/.local/bin/colorfy", line 7, in <module>
exec(compile(f.read(), __file__, 'exec'))
File "~/Git/github/colorfy/bin/colorfy", line 68, in <module>
w.export(outputs, outPath)                                                                                                                                                                                       File "~/Git/github/colorfy/colorfy/colorfy.py", line 103, in export
f = open(path + self._dictFileNames[dd], 'w')
KeyError: 'T'
```

**Comment by SebastianSemper** [comment]
Fixed. Closing.
