### ISSUE TITLE
Colorfy exists ungrafefully when input file is not found

### ISSUE THREAD

**Issue by ChristophWWagner** [EMS-TU-Ilmenau/colorfy#6]
When specifying an input argument that leads to an invalid input file location, colorfy currently produces a quite ugly exception. This should be polished to be more informative to the user in my opinion. As this is not an abnormal program abortion there should be a distinct message.

```
user:~/Git/github/colorfy/demo$ colorfy -p bla
Traceback (most recent call last):
File "~/Git/github/colorfy/colorfy/colorfy.py", line 39, in __init__
open(self._path + '.json')
FileNotFoundError: [Errno 2] No such file or directory: 'bla.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/nutzer/.local/bin/colorfy", line 7, in <module>
exec(compile(f.read(), __file__, 'exec'))
File ~/Git/github/colorfy/bin/colorfy", line 61, in <module>
w = colorfy.Workspace(inPath) # before: w=Workspace(inPath)
File "~/Git/github/colorfy/colorfy/colorfy.py", line 41, in __init__
raise (FileNotFoundError)
FileNotFoundError
```

**Comment by SebastianSemper** [comment]
Agreed, proceed.
